■Git Hubには、mainではエラーになる

PS C:\temp\pythonProject1\streamlit\CloudTech_Splint7> git push -u origin main	←	main だとエラーになる
error: src refspec main does not match any
error: failed to push some refs to 'https://github.com/godspeed2nd/streamlit_web_app.git'

PS C:\temp\pythonProject1\streamlit\CloudTech_Splint7> git push -u origin master ←	master だとエラーにならない
Enumerating objects: 8, done.
Counting objects: 100% (8/8), done.
Delta compression using up to 4 threads
Compressing objects: 100% (6/6), done.
Writing objects: 100% (8/8), 78.89 KiB | 7.89 MiB/s, done.
Total 8 (delta 1), reused 0 (delta 0), pack-reused 0 (from 0)
remote: Resolving deltas: 100% (1/1), done.
To https://github.com/godspeed2nd/streamlit_web_app.git
 * [new branch]      master -> master
branch 'master' set up to track 'origin/master'.
PS C:\temp\pythonProject1\streamlit\CloudTech_Splint7> 

■再度、ローカルでファイルを追加した後、git hubにアップロードするには

add -> commit -> push 

とする

git add -A
git commit -m "3rd commit"
git push -u origin master

 